# Generated by Django 2.2.6 on 2022-07-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('ingredients', models.TextField()),
                ('preparation', models.TextField()),
                ('preparation_time', models.IntegerField()),
                ('potion', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
